<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<!-- The following target is a workaround for https://github.com/dotnet/aspnetcore/issues/59625 -->
	<Target
            Name="Workaround_ResolveBuildCompressedStaticWebAssetsConfiguration"
            BeforeTargets="ResolveBuildCompressedStaticWebAssetsConfiguration">
		<!-- Remove any duplicate items from StaticWebAssets -->

		<ItemGroup>
			<StaticWebAsset_NoDuplicates />
		</ItemGroup>

		<RemoveDuplicates Inputs="@(StaticWebAsset)">
			<Output TaskParameter="Filtered" ItemName="StaticWebAsset_NoDuplicates" />
		</RemoveDuplicates>

		<ItemGroup>
			<!-- Clear StaticWebAsset -->
			<StaticWebAsset Remove="@(StaticWebAsset)" />

			<!-- Copy filtered list to StaticWebAsset -->
			<StaticWebAsset Include="@(StaticWebAsset_NoDuplicates)" />
		</ItemGroup>
	</Target>

</Project>


