<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<!-- HIER KANN DEIN KUNDE JETZT KONFIGURIEREN: -->
		<AiTranslatorApiKey>sk-or-abc-123</AiTranslatorApiKey>
		<AiTranslatorContext>Dies ist eine medizinische App zur Patientenverwaltung. Nutze formelles Deutsch (Sie) und präzise Fachbegriffe.</AiTranslatorContext>
		<AiTranslatorGlossaryPath>$(ProjectDir)translation_glossary.txt</AiTranslatorGlossaryPath>
		<!-- Erlaubt nun flexible Kombinationen wie: release, publish -->
		<!--<AiTranslatorMode>debug, release, publish</AiTranslatorMode>-->
		<AiTranslatorMode>debug, release, publish</AiTranslatorMode>
		<SupportedLanguage>en, it</SupportedLanguage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="OsmSharp" />
		<PackageReference Include="SearchPioneer.Lingua" />
	</ItemGroup>
	<ItemGroup>
		
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Locales\Resources.Designer.cs">
			<DependentUpon>Resources.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Locales\Resources.ar.resx">
			<SubType>Designer</SubType>
		</EmbeddedResource>
		<EmbeddedResource Update="Locales\Resources.de.resx">
			<SubType>Designer</SubType>
		</EmbeddedResource>
		<EmbeddedResource Update="Locales\Resources.resx">
			<SubType>Designer</SubType>
			<CustomToolNamespace>WpftranlationTestApp.Locales</CustomToolNamespace>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>



	<!--<Import Project="..\..\Libraries\NetAI.ResxTranslator.Tasks\build\NetAI.ResxTranslator.Tasks.targets"
			Condition="Exists('..\..\Libraries\NetAI.ResxTranslator.Tasks\build\NetAI.ResxTranslator.Tasks.dll')" />-->




</Project>