<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>

		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Bcl.Memory" />
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
	  <PackageReference Include="Newtonsoft.Json" />
	  <PackageReference Include="Scriban" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
		<PackageReference Include="Microsoft.Build.Locator"  ExcludeAssets="runtime" PrivateAssets="all"/>
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild"  ExcludeAssets="runtime" PrivateAssets="all"/>
	</ItemGroup>

	<PropertyGroup Condition="$(TargetFramework.StartsWith('netstandard'))">
		<DefineConstants>$(DefineConstants);NETSTANDARD;NETSTANDARD2_0</DefineConstants>
	</PropertyGroup>

</Project>