<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Xunit.StaFact" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="System.Threading.Tasks" />
    <PackageReference Include="System.Threading" />
    <PackageReference Include="System" />
    <PackageReference Include="System.Collections" />
    <PackageReference Include="System.Linq" />
    <PackageReference Include="System.Reflection" />
    <PackageReference Include="System.Runtime" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\UI\WpftranlationTestApp\WpftranlationTestApp.csproj" />
    <ProjectReference Include="..\..\..\src\Libraries\NetAI.TestGenerator.Core\NetAI.TestGenerator.Core.csproj" />
  </ItemGroup>
</Project>